#!/usr/bin/perl -w

# Generate vectors.S, the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.

print "# generated by vectors.pl - do not edit\n";
print "# handlers\n";
print ".globl alltraps\n";

my $mode64 = @ARGV && $ARGV[0] eq 'x86_64';
for (my $i = 0; $i < 256; $i++) {
    print ".globl vector$i\n";
    print "vector$i:\n";
    if (!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)) {
        if ($mode64) {
            print "  pushq \$0\n";
        } else {
            print "  pushl \$0\n";
        }
    }
    if ($mode64) {
        print "  pushq \$$i\n";
    } else {
        print "  pushl \$$i\n";
    }
    print "  jmp alltraps\n";
}

print "\n# vector table\n";
print ".data\n";
print ".globl vectors\n";
print "vectors:\n";
for (my $i = 0; $i < 256; $i++) {
    if ($mode64) {
        print "  .quad vector$i\n";
    } else {
        print "  .long vector$i\n";
    }
}

# sample output:
#   # handlers
#   .globl alltraps
#   .globl vector0
#   vector0:
#     pushl $0
#     pushl $0
#     jmp alltraps
#   ...
#   
#   # vector table
#   .data
#   .globl vectors
#   vectors:
#     .long vector0
#     .long vector1
#     .long vector2
#   ...

