name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [i686, x86_64]
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential clang clang-tidy clang-format python3-pip qemu-system-i386 qemu-system-x86_64
        pip3 install pre-commit
    - uses: pre-commit/action@v3.0.0
    - name: Build Swift components
      run: swift/build_swift.sh
    - name: Configure
      run: cmake -S . -B build -G Ninja -DARCH=${{ matrix.arch }}
    - name: Build
      run: ninja -C build qemu-nox
    - name: Run unit tests
      run: pytest -q
    - name: Run fuzz smoke test
      run: python3 scripts/swift_fuzz.py -runs=1
    - name: Clean
      run: rm -rf build
