name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [i686, x86_64]
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: sudo apt-get update -y && sudo apt-get install -y build-essential qemu-system-i386 qemu-system-x86_64
    - name: Build
      run: make ARCH=${{ matrix.arch }} QEMU=echo qemu-nox
    - name: Clean
      run: make clean
