name: lint-and-annotate

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter:
          - { id: "shellcheck", cmd: "files=$(git ls-files '*.sh'); [ -n \"$files\" ] && shellcheck -f gcc $files" }
    steps:
      - uses: actions/checkout@v4
      - name: Install linter runtime deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck
      - name: Run ${{ matrix.linter.id }} & feed Reviewdog

        uses: reviewdog/reviewdog@v0.17.4

        with:
          name: ${{ matrix.linter.id }}
          reporter: github-pr-check
          filter_mode: diff_context
          fail_level: error
          run: ${{ matrix.linter.cmd }}
          level: warning
      - name: Emit summary
        if: always()
        run: reviewdog -reporter=local -format=rdjson -f .rdjson > $RUNNER_TEMP/rd.json
